version: "3.8"

services:
  tetris-arena:
    build: .
    environment:
      - NODE_ENV=production
      - APP_PUBKEY=${APP_PUBKEY}
      - NODE_RPC_URL=${NODE_RPC_URL:-https://alpha2.usernodelabs.org}
    ports:
      - "3333:3333"
    restart: always
