version: "3.8"

services:
  snake:
    build: .
    ports:
      - "3300:3300"
    environment:
      - PORT=3300
      - APP_PUBKEY=ut1zvhmxlhmv95cgzaph6cpv0rrcrn29gr4xkdj9fuykc6648hmvgksmkfua6
    volumes:
      - ../..:/app/upstream:ro
    restart: unless-stopped
