services:
  falling-sands:
    build:
      context: ..
      dockerfile: falling-sands/Dockerfile
    container_name: falling-sands
    environment:
      PORT: "3333"
    ports:
      - "3333:3333"
    restart: unless-stopped
